{% set name = "sentinel" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sentinel-{{ version }}.tar.gz
  sha256: f28143aa4716dbc8f6193f5682176a3c33cd26aaae05d9ecf66c186a9887cc2d

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry
  run:
    - python >={{ python_min }},<4.0
    - poetry

test:
  imports:
    - sentinel
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/eddieantonio/sentinel
  summary: Create sentinel objects, akin to None, NotImplemented, Ellipsis
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BubblyOrca
    - mxr-conda
