{% set name = "sentinel" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sentinel-{{ version }}.tar.gz
  sha256: 190928f9951af6e94a1f84eefcaed791c28097dd152b88e988906be300451fd2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry
  run:
    - python >=3.6,<4.0
    - poetry

test:
  imports:
    - sentinel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/eddieantonio/sentinel
  summary: Create sentinel objects, akin to None, NotImplemented, Ellipsis
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BubblyOrca
    - mxr-conda
